version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Zip Lambda function
          command: zip -r Hive_to_Slack.zip lambda_function.py
      - run:
          name: Deploy to S3
          branch: master
          command: aws s3 cp Hive_to_Slack.zip s3://thehive-slack-webhook/ --region us-east-1

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
